### ISSUE TITLE
HTML-Ausgabe parsen

### ISSUE THREAD

**Issue by jacboy** [ManuelBauer/Android-RssReader-Tutorial#1]
Es wäre gut, wenn die App das HTML richtig parst oder zumindest als Text darstellt.
![screenshot_2015-08-19-02-50-03](https://cloud.githubusercontent.com/assets/6690861/9346472/9834ef12-461d-11e5-92bc-e1f6ac07b365.png)

**Comment by ManuelBauer** [comment]
Hi,
danke erst mal für das Melden des Issues.
Es ist aktuell nicht geplant weitere Features zu integrieren, da dieses Repository den Stand des damaligen Tutorials widerspiegeln soll :wink: 

Klar, die App ist nicht perfekt, aber sollte einen möglichst einfachen Einstieg in die Android Programmierung bieten.

Allerdings als kleiner Hinweis: Man kann über die Methode `Html.fromHtml()` HTML parsen und das Ergebnis dann dem TextView hinzufügen.

```
Html.fromHtml(rssItem.getDescription());
```

Prinzipiell könnte man sehr viele Funktionen noch integrieren (Evtl. als Anreiz zum Programmieren):
- ViewHolder Pattern integrieren (oder RecyclerView verwenden) um die Performance der Liste zu erhöhen
- Endless Scrolling mit automatischen Nachladen von Beiträgen
- Caching um die App auch Offline zu nutzen bzw. um einen schnellen Start zu gewährleisten
- Bild-Vorschau in die Liste integrieren (sehr empfehlenswerte Library zum Laden von Bildern wäre: http://square.github.io/picasso/)
- In-App Ansicht des vollständigen Beitrags
- Und noch vieles mehr :smile: 

Happy Coding :smiley:
